services:
  easy-catalogs:
    build: .
    container_name: easy-catalogs
    ports:
      - "7171:7171"
    environment:
      - PORT=7171
      - ADDON_URL=http://localhost:7171
      - NODE_ENV=production
      - NODE_OPTIONS=--dns-result-order=ipv4first
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.default.disable_ipv6=1
    devices:
      - /dev/net/tun
    restart: unless-stopped
    volumes:
      - ./data:/app/data
